### ISSUE TITLE
How can I complete the bonding of domain name and VPS IP address on CloudFlare？

### ISSUE THREAD

**Issue by JiangWenqi** [KonaisPC/v2ray-apache-ws#1]
I think you can copy the post you posted on  [品葱](pincong.rocks) to the `README` on the weekend.

**Comment by JiangWenqi** [comment]
And I think I can write another `Dockerfile` for this script. Fucking GFW!

**Comment by KonaisPC** [comment]
Oh yes! Thank you for your kind advice! I'll add the PinCong post to README now. As for the Dockerfile, I'll be pretty much appreciated if you could help me write this. To be more clear, everyone will be appreciated I bet.
